### ISSUE TITLE
Arduino IDE 2.3.2 pulls an old 2.1.0 version and fails miserably.

### ISSUE THREAD

**Issue by drf5n** [PaulStoffregen/FrequencyTimer2#8]
Please use this form only to report code defects or bugs.

For any question, even questions directly pertaining to this code, post your question on the forums related to the board you are using.

Arduino: forum.arduino.cc
Teensy: forum.pjrc.com
ESP8266: www.esp8266.com
ESP32: www.esp32.com
Adafruit Feather/Metro/Trinket: forums.adafruit.com
Particle Photon: community.particle.io

If you are experiencing trouble but not certain of the cause, or need help using this code, ask on the appropriate forum.  This is not the place to ask for support or help, even directly related to this code.  Only use this form you are certain you have discovered a defect in this code!

Please verify the problem occurs when using the very latest version, using the newest version of Arduino and any other related software.

----------------------------- Remove above -----------------------------

### Description

Describe your problem.

Installing FrequencyTimer2 form the Arduino IDE 2.3.2 installs a Test.pde  extension example that fails silently.

Maybe it needs a new release?

### Steps To Reproduce Problem

Install the latest version (2.1.0) of FrequencyTimer2 from the IDE (2.3.2)
Open the File/Examples/FrequencyTimer2/Test example.
Notice silent failure due to Arduino's https://github.com/arduino/arduino-ide/issues/518 bug.

Hunt through docs to find https://www.arduino.cc/reference/en/libraries/frequencytimer2/ and the link to the repository.

### Hardware & Software

Board Arduino Mega
Shields / modules used
Arduino IDE version 2.3.2
Teensyduino version (if using Teensy) n/a
Version info & package name (from Tools > Boards > Board Manager)
Operating system & version Mac Sonoma 14.2.1
Any other software or hardware? none

### Arduino Sketch

// libraries: give links/details so anyone can compile your code for the same result
Test.pde sketch from V2.1 of FrequencyTimer2

```

### Errors or Incorrect Output

Silent failure.

### suggestion

Please do a new release with the updated commits since 2015.

Also, please update the link in the library.properties file to point to the moved (but broken) https://www.arduino.cc/reference/en/libraries/frequencytimer2/  page or to the https://www.pjrc.com/teensy/td_libs_FrequencyTimer2.html link.

**Comment by PaulStoffregen** [comment]
2.2 release done

**Comment by drf5n** [comment]
Thanks.

**Comment by drf5n** [comment]
It looks like FreqMeasure and FreqCount also might be impacted by the IDE's problem with .pde files:

```
libraries % find . -name "*.pde" -print
./TinyWireM/examples/Tiny85_Temp_LCD_RTC/Tiny85_Temp_LCD_RTC.pde
./TinyWireM/examples/Tiny85_Temp_LCD/Tiny85_Temp_LCD.pde
./TinyWireM/examples/Tiny85_Temp/Tiny85_Temp.pde
./Adafruit_BMP085_Unified/examples/sensorapi/sensorapi.pde
./AccelStepper/examples/MultipleSteppers/MultipleSteppers.pde
./AccelStepper/examples/AFMotor_MultiStepper/AFMotor_MultiStepper.pde
./AccelStepper/examples/ConstantSpeed/ConstantSpeed.pde
./AccelStepper/examples/Blocking/Blocking.pde
./AccelStepper/examples/ProportionalControl/ProportionalControl.pde
./AccelStepper/examples/AFMotor_ConstantSpeed/AFMotor_ConstantSpeed.pde
./AccelStepper/examples/MotorShield/MotorShield.pde
./AccelStepper/examples/DualMotorShield/DualMotorShield.pde
./AccelStepper/examples/Quickstop/Quickstop.pde
./AccelStepper/examples/MultiStepper/MultiStepper.pde
./AccelStepper/examples/Overshoot/Overshoot.pde
./AccelStepper/examples/Bounce/Bounce.pde
./AFMotorDrawbot/examples/MotorParty/MotorParty.pde
./AFMotorDrawbot/examples/MotorTest/MotorTest.pde
./AFMotorDrawbot/examples/AFMotor_MultiStepper/AFMotor_MultiStepper.pde
./AFMotorDrawbot/examples/AFMotor_ConstantSpeed/AFMotor_ConstantSpeed.pde
./AFMotorDrawbot/examples/StepperTest/StepperTest.pde
./FreqMeasure/examples/Serial_Output/Serial_Output.pde
./FreqMeasure/examples/LCD_Output/LCD_Output.pde
./LiquidCrystal_I2C/examples/HelloWorld/HelloWorld.pde
./LiquidCrystal_I2C/examples/CustomChars/CustomChars.pde
./LiquidCrystal_I2C/examples/SerialDisplay/SerialDisplay.pde
./FrequencyTimer2/examples/Test/Test.pde
./Adafruit_LED_Backpack_Library/examples/custom_character/customgen/customgen.pde
./NXPMotionSense/OrientationVisualiser/OrientationVisualiser.pde
./FreqCount/examples/Serial_Output/Serial_Output.pde
./FreqCount/examples/LCD_Output/LCD_Output.pde
```
